Check for failure when building static-bash

diff --git a/install b/install
--- a/install
+++ b/install
@@ -533,7 +533,9 @@ stdenv.lib.overrideDerivation bash (args: {
 })
 EOF
   local bash="${dest}/chroot_builds/static_bash"
-  "$nix/bin/nix-build" -o "$bash" "${dest}/chroot_builds/static_bash.nix"
+  if ! "$nix/bin/nix-build" -o "$bash" "${dest}/chroot_builds/static_bash.nix"; then
+    error "Failed to build static bash required for chroot builds."
+  fi
   mkdir -p /etc/nix/
   echo "build-use-chroot = true" \
     >> /etc/nix/nix.conf
